name: bsml-project

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12.7

  - pip

  - pip:
      - mlflow
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn